### ISSUE TITLE
Could not open input file: sprint

### ISSUE THREAD

**Issue by hitmany** [et-nik/gameap#1]
Hello, I can't init database I receive this error.

Official docs is outdated?

**Comment by et-nik** [comment]
Hello @hitmany, partly. I'll update the documentation soon.
This is 3.0-dev version. If you want try this version:

```
git clone https://github.com/et-nik/gameap /var/www/gameap
cp .env.example .env
composer install --no-dev --optimize-autoloader
php artisan key:generate --force
```
Set database options in the `.env` file, then:
```
php artisan migrate --seed
```
Login: admin
Password: fpwPOuZD

You can use version 1.2: https://github.com/et-nik/gameap-legacy/tree/v1.2-stable
