### ISSUE TITLE
app.js:1 ReferenceError: i18n is not defined

### ISSUE THREAD

**Issue by Centoff** [et-nik/gameap#20]
Система: CentOS 7.7
Собирал и по инструкции и брал shared.
Из-за этой ошибки не дает ни переустановить сервер, ни остановить, ни запустить.

И еще постоянно лезет ошибка отсутствия файла:  GET https://........./js/lang/ru.js net::ERR_ABORTED 404

**Comment by et-nik** [comment]
i18n объект находится как раз в `/js/lang/ru.js`, который у вас не загружается.
Попробую выяснить причину, по которой это может происходить.

А больше никаких деталей нет? Ошибки в логах веб сервера или PHP-FPM?

**Comment by Centoff** [comment]
В логах все хорошо, кроме ошибки, про которую я написал в конце. 

Пробовал npm устанавливать с модулем i18n-js или как то так, не помогло

**Comment by Centoff** [comment]
Так же брал уже готовый пакет для shared хостинга - таже ошибка

Забыл уточнить, релиз последний с изменениями от 28 сентября

**Comment by et-nik** [comment]
А веб сервер какой используется? Скорее всего в нём роуты не так выставлены. Посмотрите роуты для статики. Если Nginx, то нужно обратить внимание на подобные конструкции:
```
location ~* \.(js|json|...)$ {
...
 }
```

Запрос на `js/lang/ru.js` обрабатывается через index.php, это результат обработки языковых файлов `resource/language/ru`, затем их помещение в json формат.

Может быть такое, что веб сервер при запросе `js/lang/ru.js` думает, что это запрос статики и пытается найти файл, которого нет.

Взя логика загрузки i18n объекта здесь: https://github.com/et-nik/gameap/blob/develop/routes/web.php#L113

**Comment by Centoff** [comment]
Да, действительно. Проблема была в конфиге nginx.
Спасибо за оперативную помощь.
