### ISSUE TITLE
TeamSpeak 3 Support

### ISSUE THREAD

**Issue by SugarD-x** [et-nik/gameap#27]
Is TeamSpeak 3 supported? If not, is it possible to support it?

**Comment by et-nik** [comment]
Yes. TeamSpeak 3 is supported. You should upgrade game list after panel installation (Go to **Games** -> **Upgrade Games**)

**Comment by SugarD-x** [comment]
Awesome! I haven't installed the panel yet, but that was a major part that was holding me back. Looks like I'll be switching to this panel from my old one. :)
