### ISSUE TITLE
Cron Schedule Required?

### ISSUE THREAD

**Issue by SugarD-x** [et-nik/gameap#30]
In the documentation, the manual panel installation requires that you set up a cron job with the following command:
`* * * * * cd /patch/to/gameap && php artisan schedule:run >> /dev/null 2>&1`

The other panel installation instructions make no mention of this. Is the cron job required? Also, I'm a little confused by its purpose. What exactly is it doing?

My reason for asking about this is because I'm installing the panel on a Windows Server 2016 system with IIS, and I'm trying to adapt the instructions which were written for non-Windows systems to my own. So far I have everything else working. Any help on this subject is appreciated! :)

**Comment by et-nik** [comment]
This is not required but recommended.
Some modules in the future may require cron shedule.

**Comment by SugarD-x** [comment]
Understood. Thank you!
