### ISSUE TITLE
The game mod id field is required - No mods available

### ISSUE THREAD

**Issue by SugarD-x** [et-nik/gameap#32]
When no mods are available for a specific game and you attempt to add a game server with that game, (such as "Counter-Strike: Source", for example), the creation of the game server is blocked, and displays the following error:
`The game mod id field is required.`

This even occurs when the game mod field is purposely left blank.

**Comment by et-nik** [comment]
There are no mods for some games, you need to add them yourself.
Docs here (russian only) -- http://docs.gameap.ru/ru/tutorials/additional_games.html##создание-модификации

**Comment by SugarD-x** [comment]
Understood. I thought it supported just vanilla installations too without the need for mods. I wasn't aware that it was required no matter what.

**Comment by et-nik** [comment]
I'll add more default mods. Do you need Counter-Strike: Source only?

**Comment by et-nik** [comment]
Related https://github.com/et-nik/gameap/issues/17

**Comment by SugarD-x** [comment]
Right now I'm using Counter-Strike: Source and TeamSpeak 3. (I haven't looked at TeamSpeak 3 to see the options yet). I have existing servers that I am planning to move over to your panel once I have default servers set up. Your panel is awesome. :)

**Comment by et-nik** [comment]
You should upgrade games lists (Go to Administration -> Games -> Upgrade). Update panel files if you got `isValid` error.

**Comment by SugarD-x** [comment]
The problem reported in bug #33 appears to be blocking me from doing this. The fix for the `isValid` error is the only change committed to the repo since I downloaded a copy of it a few days ago.

**Comment by SugarD-x** [comment]
Just a FYI, the Counter-Strike: Source default mod has a configuration mistake.

`+port` should be `-port`

**Comment by et-nik** [comment]
Thank you! Fixed.
