### ISSUE TITLE
Attempts to unzip the .jar file

### ISSUE THREAD

**Issue by Lorekin** [et-nik/gameap#54]
![opera_DHtaQnj2PK](https://user-images.githubusercontent.com/26692817/110094620-129c9d00-7dad-11eb-8ae2-3d612d6b6e8a.png)

**Comment by et-nik** [comment]
You have misconfigured game or mod. You specified full path to `jar` file in your repository.
`jar` isn't directory or archive with game files, it is execution file.

If you specified `/srv/gameap/repository/paper/paper-1.6.5.526.jar` in your local repository settings then change it to `/srv/gameap/repository/paper`.

If you specified `http://example.com/paper/paper-1.6.5.526.jar` in your remote repository settings then arhive `paper-1.6.5.526.jar` into zip/tar/gz archive, upload to server and specify path to this archive -- `http://example.com/paper/paper.tar.gz`

Please read the docs:
http://docs.gameap.ru/en/gameap_configure/games.html#local-repository
http://docs.gameap.ru/en/gameap_configure/games.html#remote-repository
