### ISSUE TITLE
Test GameAP Daemon AutoSetup

### ISSUE THREAD

**Issue by et-nik** [et-nik/gameap#6]
Check that the script installs and configures GDaemon.

How to check?! Go to **Dedicated Servers** -> **Create** and run autosetup script on Dedicated Server.

### Debian
* [ ] Debian 6 (Squeeze)
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager
* [ ] Debian 7 (Wheezy)
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager
* [ ] Debian 8 (Jessie)
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager
* [x] Debian 9 (Stretch)
    * [x] GDaemon Install & Configure
    * [x] Servers Control (start, restart, update)
    * [x] FileManager
* [x] Debian 10 (Buster)
    * [x] GDaemon Install & Configure
    * [x] Servers Control (start, restart, update)
    * [x] FileManager
* [ ] Debian Sid
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager

### Ubuntu
* [ ] Ubuntu 12.04 (Precise)
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager
* [ ] Ubuntu 14.04 (Trusty)
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager
* [ ] Ubuntu 16.04 (Xenial)
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager
* [x] Ubuntu 18.04 (Bionic)
    * [x] GDaemon Install & Configure
    * [x] Servers Control (start, restart, update)
    * [x] FileManager
* [x] Ubuntu 18.10 (Cosmic)
    * [x] GDaemon Install & Configure
    * [x] Servers Control (start, restart, update)
    * [x] FileManager
* [ ] Ubuntu 19.04 (Disco)
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager

### CentOS
* [x] CentOS 6
    * [ ] GDaemon Install & Configure
    * [x] Servers Control (start, restart, update)
    * [x] FileManager
* [x] CentOS 7
    * [x] GDaemon Install & Configure
    * [x] Servers Control (start, restart, update)
    * [x] FileManager
* [ ] CentOS 8
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager

### Windows
* [ ] Windows Server 2019
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager
* [ ] Windows Server 2016
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager
* [ ] Windows Server 2012
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager
* [ ] Windows Server 2008
    * [ ] GDaemon Install & Configure
    * [ ] Servers Control (start, restart, update)
    * [ ] FileManager

**Comment by et-nik** [comment]
**CentOS 6**
GameAP Starter does not stop servers correctly
GameAP Daemon produces many file descriptors (pipe)

**Comment by et-nik** [comment]
**Windows 2019** Duplicates IP addresses

**Comment by et-nik** [comment]
Windows 2019. Deleting server with files not works correctly
```
Unable to remove: boost::filesystem::remove: The process cannot access the file because it is being used by another process: "C:\gameap\servers/8fa994a6-96c0-453b-9237-d4091481e782"
```

**Comment by SugarD-x** [comment]
Windows 2019: The host auto-detection on the web panel dedicated server creation does not respect the `https://` protocol, and defaults to `http://` instead.

Edit: 

> **Windows 2019** Duplicates IP addresses

This is still an issue too.
