### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Bunker56** [et-nik/gameap#75]
А можно поподробнее про установку в Docker, а то на сервер воткнуть сильно хочется и в докере уже кое-что работает. Попробовал сбилдить, ошибки в логе полезли, а что как работает не до конца понятно и времени особо нет, чтобы плотно засесть.

**Comment by Bunker56** [comment]
Одну ошибочку, кстати уже нашел в Dockerfile PHP
    && rm -rf /tmp/* \ - слеш лишний

**Comment by Bunker56** [comment]
c .env поподробнее бы

**Comment by et-nik** [comment]
Какие ошибки полезли в лог? Если можно поподробнее про действия.

Чтобы запустить Docker окружение со всем необходимым, достаточно выполнить из корня панели:
```
docker-compose up -d
```

Затем зайти на `http://localhost:2080`, ввести логин admin и пароль fpwPOuZD

**Comment by et-nik** [comment]
Образы, которые здесь имеются, используются для разработки. 

Если нужна просто панель в докере, то можно запустить используя `gameap/gameap` образ:
```
docker run -it -p 8080:8080 gameap/gameap
```
Затем зайти на http://localhost:8080
