### ISSUE TITLE
Пустые списки

### ISSUE THREAD

**Issue by manifest571** [et-nik/gameap#80]
Добрый день, просит указать 'модификацию' и 'ай-пи адреса' (я так думаю), но сами списки при этом пусты
В админ-панели модификаций также никаких не добавлено

Версия: 3.0.0-beta9

![Screenshot_2022-04-25-01-05-20-027_com android chrome](https://user-images.githubusercontent.com/12711493/164998686-32de361f-db6f-4e32-a6ac-308763758bba.jpg)

**Comment by et-nik** [comment]
Добрый день. Если есть возможность, откройте страницу с компьютера.
Затем откройте консоль разработчика хром (F12 в браузере), после этого обновите страницу и посмотрите что будет в консоли.
Если там будут ошибки, то скиньте их сюда.

**Comment by manifest571** [comment]
Можно закрывать, после рестарта всё заработало
